version: '3.8'

services:
  celery_worker:
    container_name: celery_custom_openweb
    build: .
    command: celery worker --app=celery.app.celery --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/openwebuisearch
      - CELERY_RESULT_BACKEND=redis://redis:6379/openwebuisearch
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_db_custom_openweb
    ports:
      - "8479:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  external_search:
    network_mode: bridge
    env_file: .env
    build:
      context: .
    ports:
      - 8488:8888
    depends_on:
      redis:
        condition: service_healthy
