services:
  redis:
    image: redis:latest
    container_name: redis_db_custom_openweb
    ports:
      - "8479:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  external_search:
    network_mode: bridge
    env_file: .env
    build:
      context: .
    ports:
      - 8488:8888
    depends_on:
      redis:
        condition: service_healthy