version: '3.8'

services:
  # celery_worker:
  #   container_name: celery_custom_openweb
  #   build: .
  #   command: celery worker --app=celery.capp.celery --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis_db_custom_openweb:6379/1
  #     - CELERY_RESULT_BACKEND=redis://redis_db_custom_openweb:6379/1
  #   depends_on:
  #     redis:
  #       condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "30479:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  external_search:
    env_file: .env
    network_mode: bridge
    build:
      context: .
    ports:
      - 30488:8888
      - 30489:8889
      - 30401:9001
    depends_on:
      redis:
        condition: service_healthy
